/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatIconColors;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import controlador.ControladorPrincipal;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Valhalla Code
 */
public class VentanaPrincipal extends javax.swing.JFrame {

   controlador.ControladorPrincipal controlador;
    public VentanaPrincipal() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/hora.png")).getImage());
        setSize(70*16,70*9);
        setLocationRelativeTo(null);
    }

    public void setControlador(ControladorPrincipal controlador) {
        this.controlador = controlador;
        jMenuItemNuevaTarea.addActionListener(controlador);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPaneArbol = new javax.swing.JScrollPane();
        jTreeProyectos = new javax.swing.JTree();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPaneInfo = new javax.swing.JScrollPane();
        jPanelInfo = new javax.swing.JPanel();
        jScrollPaneEstadistica = new javax.swing.JScrollPane();
        jToolBar1 = new javax.swing.JToolBar();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemImportar = new javax.swing.JMenuItem();
        jMenuItemExportar = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemAcercaDe = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemNuevaTarea = new javax.swing.JMenuItem();

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Project Menegement");
        setAutoRequestFocus(false);

        jSplitPane2.setDividerLocation(300);

        jScrollPaneArbol.setViewportView(jTreeProyectos);

        jSplitPane2.setLeftComponent(jScrollPaneArbol);

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setToolTipText("");

        jPanelInfo.setLayout(new java.awt.BorderLayout());
        jScrollPaneInfo.setViewportView(jPanelInfo);

        jSplitPane1.setLeftComponent(jScrollPaneInfo);
        jSplitPane1.setRightComponent(jScrollPaneEstadistica);

        jSplitPane2.setRightComponent(jSplitPane1);

        jToolBar1.setRollover(true);

        jMenuArchivo.setText("Archivo");

        jMenuItemImportar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemImportar.setText("Importar Proyecto...");
        jMenuArchivo.add(jMenuItemImportar);

        jMenuItemExportar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemExportar.setText("Exportar Proyecto");
        jMenuArchivo.add(jMenuItemExportar);

        jMenuBar.add(jMenuArchivo);

        jMenuAyuda.setText("Ayuda");

        jMenuItemAcercaDe.setText("Acerca de ");
        jMenuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaDeActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItemAcercaDe);

        jMenuBar.add(jMenuAyuda);

        jMenu1.setText("Tarea");

        jMenuItemNuevaTarea.setText("Nueva Tarea");
        jMenu1.add(jMenuItemNuevaTarea);

        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaDeActionPerformed
        AcercaDe acercaDe = new AcercaDe(this,true);
        acercaDe.setVisible(true);
    }//GEN-LAST:event_jMenuItemAcercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    public javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemAcercaDe;
    public javax.swing.JMenuItem jMenuItemExportar;
    public javax.swing.JMenuItem jMenuItemImportar;
    public javax.swing.JMenuItem jMenuItemNuevaTarea;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanelInfo;
    private javax.swing.JScrollPane jScrollPaneArbol;
    public javax.swing.JScrollPane jScrollPaneEstadistica;
    public javax.swing.JScrollPane jScrollPaneInfo;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JTree jTreeProyectos;
    // End of variables declaration//GEN-END:variables
}
